### ISSUE TITLE
Oklara instruktioner

### ISSUE THREAD

**Issue by WheresMarco** [hg222dt/positioning_service#1]
Kände det oklart hur man fick igång applikationen. Hitta inga instruktioner för det.

Men jag körde `bundle install` & `rake db:setup` så verkar det fungera.

Fick dock problem med att köra `rails s` på Nitrous så jag var tvungen att binda IP-adressen till 0.0.0.0 (`rails s -b 0.0.0.0`)  - men det är troligtvis ett Nitrous-problem och inte p.g.a. din app.

**Comment by hg222dt** [comment]
Korrekt, jag missade de grundläggande instruktionerna. Fixar vi.
