### ISSUE TITLE
Fält i registrering

### ISSUE THREAD

**Issue by WheresMarco** [hg222dt/positioning_service#2]
Blev förvånad när jag kunde registrera mig utan att fylla i `Website name` och `Website url`. Ska dom vara valfria att fylla i? 

Annars sätt en validering i modellen för User som tvingar dom.

**Comment by hg222dt** [comment]
Förstår din tanke! Men jag tycker att användaren ska kunna skaffa sig en nyckel utan att behöva fylla i adress. Exempelvis så det fungerar på Googles Api-console, då icke ifylld-adress betyder att nyckeln fungerar på vilken sida som helst. Men får se hur jag gör med det.
