### ISSUE TITLE
Tydligare meddelanden

### ISSUE THREAD

**Issue by WheresMarco** [hg222dt/positioning_service#3]
En designåsikt - borde vara tydligare och mer förklarande felmeddelanden till användaren. 

'logged out' och 'Failed' som meddelanden är inte dom mest förklarande meddelanden.

Samma när man registrera sig. Kanske ett välkommnen-meddelande till användaren som visar att allt gick bra.

**Comment by hg222dt** [comment]
Good input. När tid ges.. ;)

**Comment by 1dv450** [comment]
+1
