### ISSUE TITLE
Kunde inte logga in som admin

### ISSUE THREAD

**Issue by WheresMarco** [hg222dt/positioning_service#4]
Kunde inte logga in som admin med uppgifterna som fanns i readme. 

Kollar jag igenom db-mappen och `seeds.rb` kan jag inte se att admin-kontot skulle skapas när jag kör `db:setup` t.ex.

Lägga till admin-konto vid installation alternativt finnas något sätt att skapa admin-konton skulle förenkla.

**Comment by hg222dt** [comment]
Hallå Marco

Tack för bra input. Tyvärr hade jag några småproblem med lösenords-skapandet när jag skulle seeda, och pga tidsbrist löste jag admin-skapandet på annat sätt. 

Du gör såhär:
1. Avkommentera rad 13 i users_controller
2. Skapa en ny användare under länken "Registrera" som finns på root-sidan. 
3. Kommentera rad 13 igen för att kunna skapa vanliga användare.

OBS. Det fanns en bug i appen tidigare som den andra peer-reviewaren hittade. Viktigt därför att du kör den allra senaste releasen! :)

**Comment by hg222dt** [comment]
Nu! Lyckades jag att skapa en seedad admin. Så om du kör db:seed, kommer du få en admin att testa.

/Henrik

**Comment by hg222dt** [comment]
@WheresMarco , men använd då den senaste releasen.
