### ISSUE TITLE
Allmän feedback

### ISSUE THREAD

**Issue by WheresMarco** [hg222dt/positioning_service#5]
Efter att ha kollat igenom din app så tycker jag att det saknas lite saker bland annat tydliga instruktioner för att installera applikationen.

Kan inte heller testa admin då det kontot saknas när jag kör igång applikationen.

Kollar man koden så finns det lite metoder i User-controllern som skulle kunna flyttas till en helper. T.ex. `login` och `logout`. 

Som jag ser så har du delat upp admin-användare och vanliga via controllers. I min applikation så är admin en likadan användare som alla andra, enda skillnaden är att jag har ett extra fält som har ett booleskt-värde som jag kollar om den är true. Då är användaren en admin. På så sätt kan man slå ihop dom två controllers.

Gillar att du loggar in en när man registrerar sig, då slipper man fylla i samma uppgifter igen.

För admin-metoderna tror jag det hade varit bättre att ha dom i en admin-controller istället bland User-metoderna.

Men fixa instruktioner för installation så kommer den att vara godkänd.

**Comment by hg222dt** [comment]
Tack för feedback!
Som sagt, följ mina instruktioner i tidigare issue angående admin, så ska det lösa sig.
Kollar på resterande bitar!

**Comment by 1dv450** [comment]
Bra feedback och kommentarer! Kul att se att du tar till dig av feedbacken och fixade till "felet"  som fanns. Bra!
