### ISSUE TITLE
Samladde issues, via mail

### ISSUE THREAD

**Issue by em222iv** [hg222dt/positioning_service#6]
Erik Magnusson em222iv@student.lnu.se
12 feb. (4 dagar sedan)

till Henrik 
Hej Henrik,
Jag har tittat lite på din rails applikationen och har ett par frågor.

Jag kan inte komma åt adminsidan, jag ser inte att det genereras någon admin nånstans heller. Jag försökte lägga till en admin i din seed-fil för att få till ett inlog, men gick bet även där. 

Jag behöver detta för att kunna slutföra reviewen.
Resten av applikationen verkar dock fungera bra.

Hoppas allt är bra i övrigt!
Mvh,
Erik Magnusson
em222iv

Henrik Gudmundsson via gmail.com 
12 feb. (4 dagar sedan)

till mig 
Hallå Erik! 
Ledsen att det inte fungerat smärtfritt! 

Hmm, det ska finnas en hårdkodad admin som går att logga in på via '/admin_login_page' och där logga in med användarnamn "admin@admin.se" och lösenordet "hejhej".

Om detta inte fungerar så ska det gå att skapa en admin genom att avkommentera rad 13 i users_controller, och sedan i browsern registrera en ny användare under länken "Registrera" på root-sidan. 

Hoppas detta funkar för dig! :)

Henrik

Thu Feb 12 2015 at 11:20:12 AM skrev Erik Magnusson em222iv@student.lnu.se:

Erik Magnusson em222iv@student.lnu.se
12 feb. (4 dagar sedan)

till Henrik 
Hej igen Henrik. tack för snabbt svar.

Jag har testat ytterligare och det verkar tyvärr inte fungera så bra:
Hårdkokad användare fungerar ej.

Att skapa egen användare ger först felmed:

undefined local variable or method `user' for #<#Class:0x007ffd796775e0:0x007ffd79233c18>

för <li><%= user.email %> i admin_view

Jag tog bort denna från vyn för att komma in.

Då kom detta.

undefined local variable or method `user' for #<#Class:0x007ffd796775e0:0x007ffd791fbed0>

för rad: <%= link_to " Ta bort nyckel", admin_revoke_key_path(:user => user) %> i admin_view

Efter att ta bort nästan alla user variabler ur vyn så kommer jag in på sidan men då har jag istället ingen funktionalitet kvar som admin.

Jag kan inte heller komma åt nån vy för att ta bort användare eller användares nycklar heller.

Ifall detta fungerar för dig så kanskedu kan testa att ladda ner ditt eget repo från github och testa det(om du inte redan gjort det) och se om du får liknande problem.

Mvh,
Erik

Den 12 februari 2015 11:38 skrev Henrik Gudmundsson hg222dt@student.lnu.se:

Henrik Gudmundsson via gmail.com 
12 feb. (4 dagar sedan)

till mig 
Hallå igen, jag laddar ner mitt eget och återkommer!

Thu Feb 12 2015 at 12:30:08 PM skrev Erik Magnusson em222iv@student.lnu.se:

Henrik Gudmundsson via gmail.com 
12 feb. (4 dagar sedan)

till mig 
Hallå igen, 

jag hittade vad felet var här. En merge-konflikt hade uppstått när jag gjort min sista commit. Hade uppenbarligen inte testat tillräckligt noggrant efter det, men nu skapade jag en ny release som du kan testa utifrån. https://github.com/hg222dt/positioning_service/releases/tag/v1.2

//Henrik

Thu Feb 12 2015 at 12:31:35 PM skrev Henrik Gudmundsson hg222dt@student.lnu.se:

Henrik Gudmundsson via gmail.com 
12 feb. (4 dagar sedan)

till mig 
Och nu fungerar det att logga in på admin-sidan med användarnamn "admin@admin.se" och lösenord "hejhej"

Thu Feb 12 2015 at 12:48:26 PM skrev Henrik Gudmundsson hg222dt@student.lnu.se:

Erik Magnusson em222iv@student.lnu.se
12 feb. (4 dagar sedan)

till Henrik 
Hallåhallå igen!

Nu fungerar adminsidan!
Jag vet inte om det är mig det är fel på men jag kommer fortfarande inte in med din hårdkodade admin, men det spelar ju ingen roll!

Tycker ser fint ut och det enda jag kan tänka mig ifrågasätta är att det inte går att generera nya nycklar som varken admin eller användare, när den blivit borttagen.

Ifall det måste skapas en ny användare för att generera nyckel så kanske det är bäst att admin kan radera användaren i sig istället.

Ha det fint! 

Mvh,
Erik

**Comment by 1dv450** [comment]
Bra kommunikation för att lösa de problem som fanns!
