### ISSUE TITLE
Kommentarer

### ISSUE THREAD

**Issue by 1dv450** [hg222dt/positioning_service#7]
Jag håller med om många kommentarer kring felmeddelanden, design (speciellt registreringsformuläret, visande av nycklen m.m.) samt att jag också hade problem med admin-inloggningen (körde senaste releasen). Rent funktionsmässigt verkar det annars fungera men viss kodstruktur kunde gjorts lite refactoring på (användandet av helpers)

**Comment by hg222dt** [comment]
Tack för input från dig med! Håller med själv om det mesta. Ska se över det.
