### ISSUE TITLE
Problem med startande av applikationen

### ISSUE THREAD

**Issue by jh222vp** [hg222dt/positioning_service#8]
Hej Henrik

Jag har försökt att på alla sätt och vis försöka få igång ditt API, men tyvärr utan framgång :(
Det verkar vara något problem med att känna av servern då jag kör mitt från nitrous.io (Samma som John på föreläsningarna). Har testat i både production mode samt vanliga servern (rails s) men ingenting lyckas. Försökt att modifiera serverpids och ta bort dem men inte heller det lyckas.

Kan det vara något som inte står med i ReadMe filen som sparkar igång applikationen? Följt din punktlista till punkt och pricka men ändå så lyckas jag tyvärr inte. 

Har kikat lite på din kod och den ser bra ut, hade kanske önskat lite mer kommentarer här och där (men ska inte gnälla för mycket om det då jag inte heller är särskillt bra på att komma ihåg att skriva dem ;) ) Kul att se att du har skrivit tester och du verkar hålla en bra konsekvent standard på koden där du underviker dry.

**Comment by hg222dt** [comment]
Hallå där :)

Det var ju himla märkligt! Jag kör ju själv i mac, så har ingen aning om hur nitrous fungerar eller vad som kan vara fel. Vad jag vet är att mitt projekt fungerar fint att köra igång servern på här, oh jag har även testar att ladda ner mitt projekt pånytt från github i zip-format för att köra det, vilket också fungerar finfnt. Så det är ju ett skumt problem! 

Ja, för att köra servern ska det räcka med att ladda ner projektet och skriva kommandona "bundle install" och rake db:setup".

Taggar John här så han kommer med i konversationen - @1dv450 
John, vet du något om detta är ett vanligt problem med Nitrous? Och vad ska vi göra åt det? Jag har lite svårt att felsöka ett problem av denna karaktär känner jag.. :(

**Comment by 1dv450** [comment]
@jh222vp  Vad får du för felmeddelande när du kör? Console borde ge något felmeddelande man kan gå på?

Testa starta servern med  "rails server -b 0.0.0.0"

**Comment by jh222vp** [comment]
@1dv450 Fick igång den med ditt kommando :)

**Comment by 1dv450** [comment]
Japp jag också nu när jag testade :) Bra bra! Kör hårt!

**Comment by jh222vp** [comment]
@hg222dt Nu har jag testat med din PostMan fil också och inte bara granskat koden :)
I grund och botten tycker jag det verkar fungera bra och tycker du har gjort ett bra jobb med dina instruktioner till mig (Att servern inte startade hos mig är självklart inte ditt fel). Tydligt vad man ska göra och var man ska knappa in sin API. 

En liten sak jag reagerade på var dock att när man ser sin URL i json posten så verkar den vara kodad så man ser "localhost:3000" och alltså inte min url som jag körde ifrån (Nitrous.io/blahblah/blah/). Den länkar alltså fel.

Annars tycker jag det ser bra ut det mesta och du har förklarat bra :+1:

**Comment by hg222dt** [comment]
@jh222vp Aha! hmm går det att känna av automatiskt vilken root sidan har? Jag tänker nämligen att detta inte är något problem senare när man ändå har en statisk host-url och hela tiden anropar api:et mot denna. Men har du något tips på hur jag kan lösa detta?
